### ISSUE TITLE
A command error occurred Shillchains Ashita

### ISSUE THREAD

**Issue by Bel85** [Ivaar/Ashita-addons#10]
Hi,

Trying to use Skillchains on the Eden server. The addon is loaded, but I can't see anything in game and I keep getting a message saying "A command error occurred" when using commands like / sc move etc.

**Comment by Ivaar** [comment]
No one has reported broken commands on retail. I can't imagine what the issue could be, unless eden distributes their own locked down version of ashita. You may have better luck asking on eden discord.
