### ISSUE TITLE
Dragoon jump skill triggers "Gale Axe" usage on skillchains

### ISSUE THREAD

**Issue by sasaan** [Ivaar/Ashita-addons#11]
When using jump on dragoon skillchains acts as if gale axe was used prompting what you can skillchain off of. This happens on main and sub, and if others use jump as well.
![image](https://user-images.githubusercontent.com/45071653/84009538-69ba3200-a941-11ea-9d36-1a17114cd4cb.png)

**Comment by Ivaar** [comment]
SE adjusted jumps and other mob target abilities to use the same action category as weapon skills and I forgot to adjust ashita skillchains to handle that. I'll push a fix soon.

**Comment by Ivaar** [comment]
I think its fixed, can you verify?

**Comment by sasaan** [comment]
Just verified, issue seems to be fixed
