### ISSUE TITLE
calling packet doesnt exist

### ISSUE THREAD

**Issue by fragfox** [Ivaar/Ashita-addons#2]
maybe this hasnt been updated to work on ashita v3 but it calls for packet lib that doesnt seem to exist in ashita so i get error

**Comment by Ivaar** [comment]
When I get a chance I'll check out the new api and libs, it shouldn't be too much trouble to port the addons to v3.

**Comment by Crysez** [comment]
Sorry to prod on this one, but having the same issue.  Would it still be possible to add ashita v3 support?

**Comment by Ivaar** [comment]
Sorry for the delay, which addons do you want updated for v3?

**Comment by Crysez** [comment]
Thanks for such a quick reply!

This was specifically in reference to Auctioneer.  God, that thing was awesome.

**Comment by Ivaar** [comment]
Everything looks in order. I'll port the others if anyone requests them.

**Comment by Crysez** [comment]
you da man. 

thanks very much

**Comment by fragfox** [comment]
could you possibly fix npcit to work with ashita v3 thanks :)

**Comment by Ivaar** [comment]
Updated.
