### ISSUE TITLE
Skillchains Error Anytime WS is Used

### ISSUE THREAD

**Issue by Tru14** [Ivaar/Ashita-addons#4]
[Addons] Error! Addon skillchains failed to call event render. Error: \addons\skillchains\skillchains.lua:264: bad argument #2 to 'format' (number 
expected, got nil)

**Comment by Ivaar** [comment]
Should work now, let me know if you find more bugs. It was a hasty conversion, so I expect there could be a few. If no further issues feel free to close this.

**Comment by Tru14** [comment]
That fixed it. Great addon thanks for sharing it!
