### ISSUE TITLE
SendTarget

### ISSUE THREAD

**Issue by Siushaga** [Ivaar/Ashita-addons#5]
Using SendTarget with Ashita v3 and can't seem to get it to load. 

Error while trying to load addon sendtarget. Error: \addons\sendtarget\sendtarget.lua:34: loop or previous error loading module 'events'.

Going to try to dig into it more, but is this recoded to work with Ashita v3?

**Comment by Ivaar** [comment]
Needs to be updated for Ashita v3, The name of targets module changed with the new api.
I'm not sure what else changed atm, but I'll have a look tonight.

**Comment by Siushaga** [comment]
Much appreciated, thanks for taking a look!

**Comment by Ivaar** [comment]
Updated
