### ISSUE TITLE
Sendtarget not working with ashita script txt

### ISSUE THREAD

**Issue by Squeech007** [Ivaar/Ashita-addons#7]
Hello!
Thank you for your hard work on this (and other) great Addon.
I love it. Works very good.

Did not work however when i use it in the txt script files (exec myfile.txt).
The issue seems as if the function will continue and not wait for my selection in line 1.
The mule will always cast on himself then.

Using the SE macros its all warking tho, as i said. Unfortunatly i dont use them anymore.
I really hope its easy to fix or change.
Even if not, thx anyways for this great Addon!

**Comment by Ivaar** [comment]
I don't believe <st> works in .txt scripts, try keybinds.
