### ISSUE TITLE
Boxdestroyer Failed to call event incoming_packet

### ISSUE THREAD

**Issue by Shadowgar** [Ivaar/Ashita-addons#8]
While using the addon with a locked chest, the addon will display,

Error! addon boxdestroyer failed to call event incoming_packet. Error addons\""\boxdestroyer.lua:119: bad argument #2 to 'format' (number expect, got nil)

Then box destoryer won't work till reload

**Comment by Ivaar** [comment]
Updated. I didn't catch the message ID shift last month, Chiaia beat me to it on the windower side, which you can always check for the latest messages.lua <https://github.com/Windower/Lua/blob/dev/addons/boxdestroyer/messages.lua>
